import { ILevel } from "../componets/interfaces";

export const levels: ILevel[] = [
    {
        itemSet:[
            {id:1,color:"blue",order:1,tube:1,},
            {id:2,color:"blue",order:3,tube:1,},
            {id:3,color:"red",order:2,tube:1,},
            {id:4,color:"red",order:4,tube:1,},
            {id:5,color:"red",order:1,tube:2,},
            {id:6,color:"red",order:3,tube:2,},
            {id:7,color:"blue",order:2,tube:2},
            {id:8,color:"blue",order:4,tube:2,}
          ],
          colorCount:2,
          tubecount:3
    },
    {
        colorCount:3,
        tubecount:4,
        itemSet:[
            {id:1,color:"blue",order:1,tube:1,},
            {id:2,color:"blue",order:3,tube:1,},
            {id:3,color:"green",order:2,tube:1,},
            {id:4,color:"red",order:4,tube:1,},
            {id:5,color:"red",order:1,tube:2,},
            {id:6,color:"red",order:3,tube:2,},
            {id:7,color:"blue",order:2,tube:2,},
            {id:8,color:"blue",order:4,tube:2,},
            {id:9,color:"red",order:1,tube:3,},
            {id:10,color:"green",order:3,tube:3,},
            {id:11,color:"green",order:2,tube:3,},
            {id:12,color:"green",order:4,tube:3,}
          ]
    },
    {
        colorCount:4,
        tubecount:5,
        itemSet:[
            {id:1,color:"black",order:1,tube:1,},
            {id:2,color:"blue",order:3,tube:1,},
            {id:3,color:"black",order:2,tube:1,},
            {id:4,color:"red",order:4,tube:1,},
            {id:5,color:"red",order:4,tube:2,},
            {id:6,color:"green",order:3,tube:2,},
            {id:7,color:"blue",order:2,tube:2},
            {id:8,color:"blue",order:1,tube:2,},
            {id:9,color:"red",order:4,tube:3,},
            {id:10,color:"green",order:3,tube:3,},
            {id:11,color:"black",order:2,tube:3},
            {id:12,color:"green",order:1,tube:3,},
            {id:13,color:"blue",order:4,tube:4,},
            {id:14,color:"red",order:1,tube:4,},
            {id:15,color:"black",order:3,tube:4,},
            {id:16,color:"green",order:2,tube:4,},
          ]
    },
    {
        colorCount:4,
        tubecount:6,
        itemSet:[
            {id:1,color:"black",order:1,tube:1,},
            {id:2,color:"blue",order:3,tube:1,},
            {id:3,color:"black",order:2,tube:1,},
            {id:4,color:"red",order:4,tube:1,},
            {id:5,color:"red",order:1,tube:2,},
            {id:6,color:"green",order:3,tube:2,},
            {id:7,color:"blue",order:2,tube:2},
            {id:8,color:"blue",order:4,tube:2,},
            {id:9,color:"red",order:1,tube:3,},
            {id:10,color:"green",order:3,tube:3,},
            {id:11,color:"black",order:2,tube:3},
            {id:12,color:"green",order:4,tube:3,},
            {id:13,color:"blue",order:4,tube:4,},
            {id:14,color:"red",order:1,tube:4,},
            {id:15,color:"black",order:3,tube:4,},
            {id:16,color:"green",order:2,tube:4,},
          ]
    }
]
